#! /bin/bash
#
# Copyright (c) 2009 Sun Microsystems, Inc., 4150 Network Circle, Santa
# Clara, California 95054, U.S.A. All rights reserved.
# 
# U.S. Government Rights - Commercial software. Government users are
# subject to the Sun Microsystems, Inc. standard license agreement and
# applicable provisions of the FAR and its supplements.
# 
# Use is subject to license terms.
# 
# This distribution may include materials developed by third parties.
# 
# Parts of the product may be derived from Berkeley BSD systems,
# licensed from the University of California. UNIX is a registered
# trademark in the U.S.  and in other countries, exclusively licensed
# through X/Open Company, Ltd.
# 
# Sun, Sun Microsystems, the Sun logo and Java are trademarks or
# registered trademarks of Sun Microsystems, Inc. in the U.S. and other
# countries.
# 
# This product is covered and controlled by U.S. Export Control laws and
# may be subject to the export or import laws in other
# countries. Nuclear, missile, chemical biological weapons or nuclear
# maritime end uses or end users, whether direct or indirect, are
# strictly prohibited. Export or reexport to countries subject to
# U.S. embargo or to entities identified on U.S. export exclusion lists,
# including, but not limited to, the denied persons and specially
# designated nationals lists is strictly prohibited.
# 
# Installs the key components of a Java installation

# Resolve location of this script
    me="${BASH_SOURCE[0]}"
    while [ -h "$me" ]; do
        me=`readlink -e "$me"`
    done

me_dir=`dirname $me`
. $me_dir/ext2setup

ext2jh=/guestvm/ext2/java
java -classpath $cp $h $mc mkdir -disk $dfile -ext2path $ext2jh
java -classpath $cp $h $mc mkdir -disk $dfile -ext2path $ext2jh/lib
java -classpath $cp $h $mc mkdir -disk $dfile -ext2path $ext2jh/jre
java -classpath $cp $h $mc mkdir -disk $dfile -ext2path $ext2jh/jre/lib

# create a fake java executable to keep certin apps happy
java -classpath $cp $h $mc mkdir -disk $dfile -ext2path $ext2jh/jre/bin
java -classpath $cp $h $mc mkfile -disk $dfile -ext2path $ext2jh/jre/bin/java

# tools.jar
java -classpath $cp $h $mc copyin -disk $dfile -from $JAVA_HOME/lib/tools.jar -ext2path $ext2jh/lib

# runtime jars
dir=$JAVA_HOME/jre/lib
todir=$ext2jh/jre/lib

java -classpath $cp $h $mc copyin -disk $dfile -from ${dir}/rt.jar -ext2path $todir
java -classpath $cp $h $mc copyin -disk $dfile -from ${dir}/jce.jar -ext2path $todir
java -classpath $cp $h $mc copyin -disk $dfile -from ${dir}/jsse.jar -ext2path $todir
java -classpath $cp $h $mc copyin -disk $dfile -from ${dir}/resources.jar -ext2path $todir
java -classpath $cp $h $mc copyin -disk $dfile -from ${dir}/charsets.jar -ext2path $todir
java -classpath $cp $h $mc copyin -disk $dfile -from ${dir}/logging.properties -ext2path $todir
