#! /bin/bash
#
# Copyright (c) 2009 Sun Microsystems, Inc., 4150 Network Circle, Santa
# Clara, California 95054, U.S.A. All rights reserved.
# 
# U.S. Government Rights - Commercial software. Government users are
# subject to the Sun Microsystems, Inc. standard license agreement and
# applicable provisions of the FAR and its supplements.
# 
# Use is subject to license terms.
# 
# This distribution may include materials developed by third parties.
# 
# Parts of the product may be derived from Berkeley BSD systems,
# licensed from the University of California. UNIX is a registered
# trademark in the U.S.  and in other countries, exclusively licensed
# through X/Open Company, Ltd.
# 
# Sun, Sun Microsystems, the Sun logo and Java are trademarks or
# registered trademarks of Sun Microsystems, Inc. in the U.S. and other
# countries.
# 
# This product is covered and controlled by U.S. Export Control laws and
# may be subject to the export or import laws in other
# countries. Nuclear, missile, chemical biological weapons or nuclear
# maritime end uses or end users, whether direct or indirect, are
# strictly prohibited. Export or reexport to countries subject to
# U.S. embargo or to entities identified on U.S. export exclusion lists,
# including, but not limited to, the denied persons and specially
# designated nationals lists is strictly prohibited.
# 
#
# Guest VM is a Java virtual machine, so we provide a "java" launch command.
# However, most users will find the "run" command easier to work with.

classpath="/guestvm/image/GuestVM/bin"
vmargs=""
xtra_args=""
jar=""
vmalloc="-XX:SemiSpaceGC:Virtual"

function vm_args() {
    shift
    if [ "$vmargs" = "" ] ;
    then
      vmargs="$1"
    else
      vmargs="$vmargs $1"
    fi
    shift
}

while [ "$1" != "" ] ;
do
  case "$1" in
    "-cp" )
	    shift
	    classpath=$1
	    shift
	    ;;
    "-jar" )
	     shift
	     jar=$1
	     shift
	     ;;
    "-D"* )
	  vm_args
	  ;;
	  
    "-X"* )
	    vm_args
	    ;;

    "-XX"* )
	     vm_args
	     ;;

    * )
	if [ "$xtra_args" = "" ] ;
	then
	  xtra_args=$1
	else
	  xtra_args="$xtra_args $1"
	fi
	shift
	;;
  esac
done

if [ "$jar" == "" ] ;
then
  cp="-classpath $classpath"
else
  cp="-jar $jar"
fi

extra="$vmargs $vmalloc $cp $xtra_args"
xm create -c xmconfigs/domain_config_generic extra="$extra" name=GuestVM
